//! Rendering the compat files.
//!
//! The socket is the store; these files are a compatibility artifact of it,
//! for the software that reads trust from a path — which today is nearly all
//! of it. `GenerateLinuxTrustFiles` decides whether they exist at all.
//!
//! Three artifacts, because this build of OpenSSL is configured
//! `--openssldir=/etc/ssl` and the ecosystem is not of one mind:
//!
//! | Path | Who reads it |
//! |---|---|
//! | `certs/ca-certificates.crt` | Go probes it first; most software is configured with it |
//! | `cert.pem` | OpenSSL's default `CAfile` for this build |
//! | `certs/<subject-hash>.<n>` | OpenSSL's default `CApath` |
//!
//! The hashed directory is not decoration. A `CApath` lookup that finds a
//! stale file for a distrusted root would keep trusting it, so the directory
//! is replaced **atomically**: the new one is built alongside and exchanged
//! in a single syscall. There is no moment at which the directory holds a
//! mixture of the old set and the new.

use std::fs;
use std::io;
use std::io::ErrorKind;
use std::os::unix::ffi::OsStrExt;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

use crate::cert;
use crate::store::{self, Composed, Entry};

/// `GenerateLinuxTrustFiles`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Compat {
    /// No files. The pure-native machine: everything asks the socket, and
    /// software that reads a path fails — visibly, with certificate errors.
    None,
    /// Rendered and kept current. The default, and what every image ships
    /// until its whole software set speaks the socket.
    #[default]
    Files,
    /// Reserved: the files served through trustd itself, per read. Treated
    /// as `Files` until it exists, if it ever does.
    Live,
}

impl Compat {
    pub fn from_dword(value: u32) -> Compat {
        match value {
            0 => Compat::None,
            2 => Compat::Live,
            _ => Compat::Files,
        }
    }

    pub fn as_dword(self) -> u32 {
        match self {
            Compat::None => 0,
            Compat::Files => 1,
            Compat::Live => 2,
        }
    }
}

const FILE_MODE: u32 = 0o644;
const DIR_MODE: u32 = 0o755;

/// The bundle's provenance header. A person opening the file should be able
/// to tell where it came from and that editing it is pointless.
fn header(roots: &[&Entry]) -> String {
    format!(
        "# Peios trust store — generated by trustd; edits are overwritten.\n\
         #\n\
         # This file is a compatibility rendering of the machine's trust store.\n\
         # It is composed from the roots the ca-certificates package ships and\n\
         # the additions and distrusts under Machine\\System\\Trust\\Certificates.\n\
         # To change what this machine trusts, use `trust add` / `trust distrust`\n\
         # or write the registry directly — never this file.\n\
         #\n\
         # {} root(s): {} shipped, {} added.\n\n",
        roots.len(),
        roots
            .iter()
            .filter(|r| r.source == libtrust::Source::Shipped)
            .count(),
        roots
            .iter()
            .filter(|r| r.source == libtrust::Source::Added)
            .count(),
    )
}

/// The compatibility bundle: ServerAuth roots, each with a comment naming it.
pub fn bundle(composed: &Composed) -> String {
    bundle_for_roots(&store::for_purpose(&composed.roots, store::SERVER_AUTH))
}

fn bundle_for_roots(roots: &[&Entry]) -> String {
    let mut out = header(roots);
    for root in roots {
        out.push_str(&format!("# {}\n", root.parsed.subject));
        if let Some(name) = &root.name {
            out.push_str(&format!("# added as {name}\n"));
        }
        out.push_str(&format!("# SHA-256 {}\n", root.parsed.fingerprint));
        out.push_str(&cert::to_pem(&root.parsed.der));
        out.push('\n');
    }
    out
}

/// Add the operation and the path to an error. A renderer does a dozen
/// filesystem operations and reports one error; without this, "Permission
/// denied" says nothing about what was denied.
fn at<'a>(operation: &'a str, path: &'a Path) -> impl FnOnce(io::Error) -> io::Error + 'a {
    move |e| io::Error::new(e.kind(), format!("{operation} {}: {e}", path.display()))
}

/// Write the files for `composed` under `root`, or remove them in
/// [`Compat::None`]. Returns the paths that now exist.
///
/// `root` is the store directory (`/system/retc/ssl` in production, a
/// temporary directory in tests).
pub fn render(root: &Path, composed: &Composed, compat: Compat) -> io::Result<Vec<String>> {
    let certs = root.join("certs");
    let cert_pem = root.join("cert.pem");

    if compat == Compat::None {
        // Leaving the files behind would leave stale trust in force, which
        // is worse than the honest breakage of having none. The directories
        // themselves stay: they are the hook's, and an empty CApath is
        // exactly as trust-free as an absent one.
        remove_if_present(&cert_pem).map_err(at("remove", &cert_pem))?;
        if certs.exists() {
            empty_dir(&certs).map_err(at("empty", &certs))?;
        }
        return Ok(Vec::new());
    }

    fs::create_dir_all(root).map_err(at("create", root))?;
    set_mode(root, DIR_MODE);

    // Build the whole directory alongside, then exchange it in one step.
    //
    // The staging directory is emptied and refilled, never created and
    // destroyed. On Peios a directory a service creates for itself comes
    // out with a descriptor that names SYSTEM and Administrators and not
    // the creator, so a least-privileged daemon can make a directory it
    // cannot then use. Both directories are made once by the pre-start
    // hook, and a rename carries a descriptor with it — so exchanging them
    // for ever keeps the grant that was stamped on each.
    let staging = root.join("certs.new");
    if staging.exists() {
        empty_dir(&staging).map_err(at("empty", &staging))?;
    } else {
        fs::create_dir_all(&staging).map_err(at("create", &staging))?;
        set_mode(&staging, DIR_MODE);
    }

    // Keep every compatibility artifact on the same purpose-filtered set.
    // The full composition remains available to purpose-aware socket clients.
    let roots = store::for_purpose(&composed.roots, store::SERVER_AUTH);
    let text = bundle_for_roots(&roots);
    let bundle_path = staging.join("ca-certificates.crt");
    write_file(&bundle_path, text.as_bytes()).map_err(at("write", &bundle_path))?;

    // OpenSSL's CApath: one PEM per root, named by subject hash, with a
    // sequence number to separate the occasional collision.
    let mut used: Vec<(String, u32)> = Vec::new();
    for root_entry in roots {
        let hash = &root_entry.parsed.subject_hash;
        let sequence = match used.iter_mut().find(|(h, _)| h == hash) {
            Some((_, n)) => {
                *n += 1;
                *n
            }
            None => {
                used.push((hash.clone(), 0));
                0
            }
        };
        let hashed = staging.join(format!("{hash}.{sequence}"));
        write_file(&hashed, cert::to_pem(&root_entry.parsed.der).as_bytes())
            .map_err(at("write", &hashed))?;
    }

    exchange(&staging, &certs).map_err(at("install", &certs))?;

    // The default CAfile is a copy rather than a link: it is read through a
    // filesystem merge, and a plain file has no resolution to get wrong.
    write_file(&cert_pem, text.as_bytes()).map_err(at("write", &cert_pem))?;

    Ok(vec![
        certs.join("ca-certificates.crt").display().to_string(),
        cert_pem.display().to_string(),
        certs.display().to_string(),
    ])
}

/// Write a file whole or not at all: a reader never sees a partial store.
fn write_file(path: &Path, contents: &[u8]) -> io::Result<()> {
    let temporary = path.with_extension("tmp");
    fs::write(&temporary, contents)?;
    set_mode(&temporary, FILE_MODE);
    fs::rename(&temporary, path)
}

/// Best-effort, and deliberately so. On Peios access is decided by the
/// security descriptor — which trustd stamps separately — not by mode bits,
/// and `chmod` may not be permitted at all. A render that failed over a
/// permission bit nothing consults would leave the machine with no trust
/// store for no reason. The mode still matters when these files are read on
/// an ordinary Linux host, so it is set where it can be.
fn set_mode(path: &Path, mode: u32) {
    let _ = fs::set_permissions(path, fs::Permissions::from_mode(mode));
}

fn remove_if_present(path: &Path) -> io::Result<()> {
    match fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e),
    }
}

/// Remove a directory's contents, leaving the directory — and its
/// descriptor — in place.
fn empty_dir(path: &Path) -> io::Result<()> {
    for entry in fs::read_dir(path)? {
        let entry = entry?;
        if entry.file_type()?.is_dir() {
            fs::remove_dir_all(entry.path())?;
        } else {
            fs::remove_file(entry.path())?;
        }
    }
    Ok(())
}

fn remove_dir_if_present(path: &Path) -> io::Result<()> {
    match fs::remove_dir_all(path) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e),
    }
}

/// Put `staging` where `live` is, atomically, and remove what was there.
///
/// `RENAME_EXCHANGE` swaps the two directories in one syscall, so no reader
/// ever sees the directory absent, half-built, or holding a mixture of the
/// old roots and the new. When `live` does not exist yet there is nothing to
/// exchange with and a plain rename is atomic on its own.
fn exchange(staging: &Path, live: &Path) -> io::Result<()> {
    if !live.exists() {
        return fs::rename(staging, live);
    }
    let from = cstring(staging)?;
    let to = cstring(live)?;
    // SAFETY: both paths are live NUL-terminated strings for the call.
    let rc = unsafe {
        libc::renameat2(
            libc::AT_FDCWD,
            from.as_ptr(),
            libc::AT_FDCWD,
            to.as_ptr(),
            libc::RENAME_EXCHANGE,
        )
    };
    if rc != 0 {
        // Note: on the failure path below the directories are renamed
        // rather than recreated, so their descriptors travel with them.
        let error = io::Error::last_os_error();
        // A filesystem without RENAME_EXCHANGE (or a kernel that lacks the
        // syscall) still gets a correct store, just with a window in which
        // the directory is the new one before the old is gone. Better than
        // refusing to render.
        if matches!(
            error.raw_os_error(),
            Some(libc::EINVAL) | Some(libc::ENOSYS) | Some(libc::ENOTSUP)
        ) || error.kind() == ErrorKind::PermissionDenied
        {
            let previous = live.with_extension("previous");
            remove_dir_if_present(&previous)?;
            fs::rename(live, &previous)?;
            fs::rename(staging, live)?;
            return remove_dir_if_present(&previous);
        }
        return Err(error);
    }
    remove_dir_if_present(staging)
}

fn cstring(path: &Path) -> io::Result<std::ffi::CString> {
    std::ffi::CString::new(path.as_os_str().as_bytes())
        .map_err(|_| io::Error::new(io::ErrorKind::InvalidInput, "path holds a NUL"))
}

/// The store directory's files, for a status reply.
pub fn rendered_paths(root: &Path) -> Vec<String> {
    let mut out = Vec::new();
    for path in [
        root.join("certs").join("ca-certificates.crt"),
        root.join("cert.pem"),
    ] {
        if path.exists() {
            out.push(path.display().to_string());
        }
    }
    out
}

/// A stable identity for the shipped bundle, so a package upgrade is noticed
/// without watching for filesystem events: its length and modification time.
pub fn stamp(path: &Path) -> Option<(u64, i64)> {
    let meta = fs::metadata(path).ok()?;
    let modified = meta
        .modified()
        .ok()?
        .duration_since(std::time::UNIX_EPOCH)
        .ok()?
        .as_secs() as i64;
    Some((meta.len(), modified))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::store::{self, Addition};
    use std::path::PathBuf;

    const COMODO: &str = include_str!("../tests/fixtures/comodo-ecc.pem");
    const NETLOCK: &str = include_str!("../tests/fixtures/netlock-arany.pem");
    const MICROSEC: &str = include_str!("../tests/fixtures/microsec-2009.pem");
    const PURPOSE_SHIPPED: &str = include_str!("../tests/fixtures/purpose-shipped.pem");
    const PURPOSE_ADDED: &str = include_str!("../tests/fixtures/purpose-added.pem");

    fn purpose_addition(purposes: &[&str]) -> Addition {
        Addition {
            name: "purpose-test".into(),
            der: cert::from_pem(PURPOSE_ADDED).remove(0),
            purposes: purposes.iter().map(|p| (*p).to_owned()).collect(),
        }
    }

    fn purpose_store(purposes: &[&str], distrust: &[String]) -> Composed {
        store::compose(
            &PURPOSE_SHIPPED.repeat(store::MINIMUM_SHIPPED),
            &[purpose_addition(purposes)],
            distrust,
            Some(1_700_000_000),
        )
        .unwrap()
    }

    /// Check the bytes in every artifact, not just the comments or names.
    /// The two synthetic fixtures deliberately have the same subject hash.
    fn assert_purpose_artifacts(root: &Path, composed: &Composed, expected: &[&str]) {
        let mut expected_der: Vec<Vec<u8>> = expected
            .iter()
            .map(|pem| cert::from_pem(pem).remove(0))
            .collect();
        expected_der.sort();
        let text = fs::read_to_string(root.join("certs/ca-certificates.crt")).unwrap();
        assert_eq!(fs::read_to_string(root.join("cert.pem")).unwrap(), text);
        assert_eq!(bundle(composed), text);
        let mut bundle_der = cert::from_pem(&text);
        bundle_der.sort();
        assert_eq!(bundle_der, expected_der, "the PEM bundle's exact DER set");

        let added = usize::from(expected.contains(&PURPOSE_ADDED));
        let shipped = expected.len() - added;
        assert!(text.contains(&format!(
            "# {} root(s): {shipped} shipped, {added} added.",
            expected.len()
        )));

        let hash = cert::parse(&cert::from_pem(PURPOSE_SHIPPED)[0], None)
            .unwrap()
            .subject_hash;
        assert_eq!(
            cert::parse(&cert::from_pem(PURPOSE_ADDED)[0], None)
                .unwrap()
                .subject_hash,
            hash
        );
        let mut names: Vec<_> = fs::read_dir(root.join("certs"))
            .unwrap()
            .map(|entry| entry.unwrap().file_name().into_string().unwrap())
            .collect();
        names.sort();
        let mut expected_names = vec!["ca-certificates.crt".to_owned()];
        let mut hashed_der = Vec::new();
        for sequence in 0..expected.len() {
            let name = format!("{hash}.{sequence}");
            let pem = fs::read_to_string(root.join("certs").join(&name)).unwrap();
            let mut certificates = cert::from_pem(&pem);
            assert_eq!(certificates.len(), 1);
            hashed_der.push(certificates.remove(0));
            expected_names.push(name);
        }
        expected_names.sort();
        hashed_der.sort();
        assert_eq!(names, expected_names, "no stale or extra hashed files");
        assert_eq!(hashed_der, expected_der, "the CApath's exact DER set");
        assert!(!root.join("certs.new").exists());
        assert!(!root.join("certs.previous").exists());
    }

    #[test]
    fn compatibility_purposes_filter_every_artifact_without_changing_the_store() {
        let root = scratch("purposes");
        let cases: &[(&[&str], bool)] = &[
            (&["CodeSigning"], false),
            (&["serverauth"], true),
            (&["CodeSigning", "sErVeRaUtH"], true),
            (&[], true), // Missing or empty registry purposes default during composition.
            (&["Unknown"], false),
            (&["ServerAuthentication"], false),
            (&[""], false), // A supplied empty name is not an empty purpose list.
        ];
        for compat in [Compat::Files, Compat::Live] {
            for &(purposes, eligible) in cases {
                let composed = purpose_store(purposes, &[]);
                let before = composed.clone();
                assert_eq!(composed.roots.len(), 2);
                let mut expected = vec![PURPOSE_SHIPPED];
                if eligible {
                    expected.push(PURPOSE_ADDED);
                }
                render(&root, &composed, compat).unwrap();
                assert_purpose_artifacts(&root, &composed, &expected);
                assert_eq!(composed, before, "rendering preserves the queryable store");
                assert_eq!(
                    store::for_purpose(&composed.roots, "CodeSigning").len(),
                    usize::from(purposes.contains(&"CodeSigning"))
                );
            }
        }
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn losing_server_auth_withdraws_old_pem_and_hash_entries() {
        let root = scratch("purpose-withdrawal");
        let before = purpose_store(&["ServerAuth", "CodeSigning"], &[]);
        render(&root, &before, Compat::Files).unwrap();
        assert_purpose_artifacts(&root, &before, &[PURPOSE_SHIPPED, PURPOSE_ADDED]);

        let after = purpose_store(&["CodeSigning"], &[]);
        render(&root, &after, Compat::Files).unwrap();
        assert_purpose_artifacts(&root, &after, &[PURPOSE_SHIPPED]);
        assert_eq!(after.roots.len(), 2, "the addition remains queryable");
        assert_eq!(store::for_purpose(&after.roots, "CodeSigning").len(), 1);
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn purpose_filtering_does_not_restore_distrusted_roots() {
        let root = scratch("purpose-distrust");
        let before = purpose_store(&["ServerAuth", "CodeSigning"], &[]);
        for (victim, survivor) in [
            (PURPOSE_ADDED, PURPOSE_SHIPPED),
            (PURPOSE_SHIPPED, PURPOSE_ADDED),
        ] {
            render(&root, &before, Compat::Files).unwrap();
            let fingerprint = cert::fingerprint(&cert::from_pem(victim)[0]);
            let after = purpose_store(&["ServerAuth", "CodeSigning"], &[fingerprint]);
            render(&root, &after, Compat::Files).unwrap();
            // The survivor must occupy hash.0 even if it previously used hash.1.
            assert_purpose_artifacts(&root, &after, &[survivor]);
            assert_eq!(
                store::for_purpose(&after.roots, "CodeSigning").len(),
                usize::from(survivor == PURPOSE_ADDED)
            );
        }
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn no_server_auth_roots_withdraws_all_compatibility_certificates() {
        let root = scratch("purpose-empty");
        let before = purpose_store(&["ServerAuth"], &[]);
        let distrust = vec![cert::fingerprint(&cert::from_pem(PURPOSE_SHIPPED)[0])];
        let after = purpose_store(&["CodeSigning"], &distrust);
        assert_eq!(after.roots.len(), 1);
        assert_eq!(store::for_purpose(&after.roots, "CodeSigning").len(), 1);
        // Keeping the old files would retain a now-distrusted shipped root
        // and an addition that no longer permits ServerAuth.
        for compat in [Compat::Files, Compat::Live] {
            render(&root, &before, compat).unwrap();
            render(&root, &after, compat).unwrap();
            assert_purpose_artifacts(&root, &after, &[]);
        }

        // The existing refusal of an entirely empty composition is unchanged.
        let mut distrust_all = distrust;
        distrust_all.push(cert::fingerprint(&cert::from_pem(PURPOSE_ADDED)[0]));
        let error = store::compose(
            &PURPOSE_SHIPPED.repeat(store::MINIMUM_SHIPPED),
            &[purpose_addition(&["CodeSigning"])],
            &distrust_all,
            Some(1_700_000_000),
        )
        .unwrap_err();
        assert!(error.contains("empty store"));
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn purpose_filtering_preserves_existing_duplicate_precedence() {
        let root = scratch("purpose-duplicates");
        let additions = [
            Addition {
                name: "shipped-duplicate".into(),
                der: cert::from_pem(PURPOSE_SHIPPED).remove(0),
                purposes: vec!["CodeSigning".into()],
            },
            purpose_addition(&["CodeSigning"]),
            purpose_addition(&["ServerAuth"]),
        ];
        let composed = store::compose(
            &PURPOSE_SHIPPED.repeat(store::MINIMUM_SHIPPED),
            &additions,
            &[],
            Some(1_700_000_000),
        )
        .unwrap();
        assert_eq!(composed.roots.len(), 2);
        assert_eq!(store::for_purpose(&composed.roots, "CodeSigning").len(), 1);
        render(&root, &composed, Compat::Files).unwrap();
        assert_purpose_artifacts(&root, &composed, &[PURPOSE_SHIPPED]);
        let _ = fs::remove_dir_all(root);
    }

    fn shipped() -> String {
        let mut text = String::new();
        for _ in 0..store::MINIMUM_SHIPPED {
            text.push_str(COMODO);
            text.push_str(NETLOCK);
            text.push_str(MICROSEC);
        }
        text
    }

    fn scratch(name: &str) -> PathBuf {
        let path =
            std::env::temp_dir().join(format!("trustd-render-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&path);
        path
    }

    #[test]
    fn a_render_produces_every_artifact_and_is_reproducible() {
        let root = scratch("all");
        let composed = store::compose(&shipped(), &[], &[], None).unwrap();
        let paths = render(&root, &composed, Compat::Files).unwrap();
        assert_eq!(paths.len(), 3);

        let bundle_path = root.join("certs/ca-certificates.crt");
        let text = fs::read_to_string(&bundle_path).unwrap();
        assert_eq!(text.matches("BEGIN CERTIFICATE").count(), 3);
        assert!(text.contains("generated by trustd"));
        // The default CAfile holds the same set.
        assert_eq!(fs::read_to_string(root.join("cert.pem")).unwrap(), text);
        // One hashed file per root, named as OpenSSL looks them up.
        for entry in &composed.roots {
            let path = root
                .join("certs")
                .join(format!("{}.0", entry.parsed.subject_hash));
            assert!(path.exists(), "missing {}", path.display());
            assert_eq!(cert::from_pem(&fs::read_to_string(&path).unwrap()).len(), 1);
        }
        // Rendering the same store again writes identical bytes.
        render(&root, &composed, Compat::Files).unwrap();
        assert_eq!(fs::read_to_string(&bundle_path).unwrap(), text);
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn a_distrusted_root_leaves_no_file_behind() {
        let root = scratch("distrust");
        let composed = store::compose(&shipped(), &[], &[], None).unwrap();
        render(&root, &composed, Compat::Files).unwrap();
        let victim = composed
            .roots
            .iter()
            .find(|r| r.parsed.subject.contains("COMODO"))
            .unwrap()
            .clone();
        let hashed = root
            .join("certs")
            .join(format!("{}.0", victim.parsed.subject_hash));
        assert!(hashed.exists());

        // Now distrust it and render again: the CApath entry must be gone,
        // or OpenSSL would keep trusting it through the directory.
        let after =
            store::compose(&shipped(), &[], &[victim.parsed.fingerprint.clone()], None).unwrap();
        render(&root, &after, Compat::Files).unwrap();
        assert!(
            !hashed.exists(),
            "a stale hashed file kept a distrusted root alive"
        );
        let text = fs::read_to_string(root.join("certs/ca-certificates.crt")).unwrap();
        assert!(!text.contains(&victim.parsed.fingerprint));
        assert_eq!(text.matches("BEGIN CERTIFICATE").count(), 2);
        // And no staging directory is left lying about.
        assert!(!root.join("certs.new").exists());
        assert!(!root.join("certs.previous").exists());
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn mode_none_removes_what_a_previous_mode_wrote() {
        let root = scratch("none");
        let composed = store::compose(&shipped(), &[], &[], None).unwrap();
        render(&root, &composed, Compat::Files).unwrap();
        assert!(root.join("cert.pem").exists());

        let paths = render(&root, &composed, Compat::None).unwrap();
        assert!(paths.is_empty());
        assert!(!root.join("cert.pem").exists());
        // The directory stays — it belongs to the pre-start hook, and its
        // descriptor is not trustd's to recreate — but nothing trusted may
        // remain inside it.
        assert_eq!(
            fs::read_dir(root.join("certs"))
                .map(|d| d.count())
                .unwrap_or(0),
            0,
            "stale trust must not survive the switch to mode 0"
        );
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn an_addition_is_named_in_the_bundle_for_a_person_reading_it() {
        let addition = Addition {
            name: "corp-ca".into(),
            der: cert::from_pem(MICROSEC).remove(0),
            purposes: vec![],
        };
        let mut text = String::new();
        for _ in 0..store::MINIMUM_SHIPPED {
            text.push_str(COMODO);
            text.push_str(NETLOCK);
        }
        let composed = store::compose(&text, &[addition], &[], None).unwrap();
        let rendered = bundle(&composed);
        assert!(rendered.contains("# added as corp-ca"));
        assert!(rendered.contains("3 root(s): 2 shipped, 1 added"));
    }

    #[test]
    fn compat_modes_map_to_the_registry_dword() {
        assert_eq!(Compat::from_dword(0), Compat::None);
        assert_eq!(Compat::from_dword(1), Compat::Files);
        assert_eq!(Compat::from_dword(2), Compat::Live);
        // Anything unrecognised renders rather than silently disabling trust.
        assert_eq!(Compat::from_dword(99), Compat::Files);
        assert_eq!(Compat::Files.as_dword(), 1);
    }
}
