//! Rendering the compat files.
//!
//! The socket is the store; these files are a compatibility artifact of it,
//! for the software that reads trust from a path — which today is nearly all
//! of it. `GenerateLinuxTrustFiles` decides whether they exist at all.
//!
//! Three artifacts, because this build of OpenSSL is configured
//! `--openssldir=/etc/ssl` and the ecosystem is not of one mind:
//!
//! | Path | Who reads it |
//! |---|---|
//! | `certs/ca-certificates.crt` | Go probes it first; most software is configured with it |
//! | `cert.pem` | OpenSSL's default `CAfile` for this build |
//! | `certs/<subject-hash>.<n>` | OpenSSL's default `CApath` |
//!
//! The hashed directory is not decoration. A `CApath` lookup that finds a
//! stale file for a distrusted root would keep trusting it, so the directory
//! is replaced **atomically**: the new one is built alongside and exchanged
//! in a single syscall. There is no moment at which the directory holds a
//! mixture of the old set and the new.

use std::fs;
use std::io;
use std::os::unix::ffi::OsStrExt;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

use crate::cert;
use crate::store::Composed;

/// `GenerateLinuxTrustFiles`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Compat {
    /// No files. The pure-native machine: everything asks the socket, and
    /// software that reads a path fails — visibly, with certificate errors.
    None,
    /// Rendered and kept current. The default, and what every image ships
    /// until its whole software set speaks the socket.
    #[default]
    Files,
    /// Reserved: the files served through trustd itself, per read. Treated
    /// as `Files` until it exists, if it ever does.
    Live,
}

impl Compat {
    pub fn from_dword(value: u32) -> Compat {
        match value {
            0 => Compat::None,
            2 => Compat::Live,
            _ => Compat::Files,
        }
    }

    pub fn as_dword(self) -> u32 {
        match self {
            Compat::None => 0,
            Compat::Files => 1,
            Compat::Live => 2,
        }
    }
}

const FILE_MODE: u32 = 0o644;
const DIR_MODE: u32 = 0o755;

/// The bundle's provenance header. A person opening the file should be able
/// to tell where it came from and that editing it is pointless.
fn header(composed: &Composed) -> String {
    format!(
        "# Peios trust store — generated by trustd; edits are overwritten.\n\
         #\n\
         # This file is a compatibility rendering of the machine's trust store.\n\
         # It is composed from the roots the ca-certificates package ships and\n\
         # the additions and distrusts under Machine\\System\\Trust\\Certificates.\n\
         # To change what this machine trusts, use `trust add` / `trust distrust`\n\
         # or write the registry directly — never this file.\n\
         #\n\
         # {} root(s): {} shipped, {} added.\n\n",
        composed.roots.len(),
        composed.roots.iter().filter(|r| r.source == libtrust::Source::Shipped).count(),
        composed.roots.iter().filter(|r| r.source == libtrust::Source::Added).count(),
    )
}

/// The bundle: every root, each with a comment naming it.
pub fn bundle(composed: &Composed) -> String {
    let mut out = header(composed);
    for root in &composed.roots {
        out.push_str(&format!("# {}\n", root.parsed.subject));
        if let Some(name) = &root.name {
            out.push_str(&format!("# added as {name}\n"));
        }
        out.push_str(&format!("# SHA-256 {}\n", root.parsed.fingerprint));
        out.push_str(&cert::to_pem(&root.parsed.der));
        out.push('\n');
    }
    out
}

/// Write the files for `composed` under `root`, or remove them in
/// [`Compat::None`]. Returns the paths that now exist.
///
/// `root` is the store directory (`/system/retc/ssl` in production, a
/// temporary directory in tests).
pub fn render(root: &Path, composed: &Composed, compat: Compat) -> io::Result<Vec<String>> {
    let certs = root.join("certs");
    let cert_pem = root.join("cert.pem");

    if compat == Compat::None {
        // Leaving the files behind would leave stale trust in force, which
        // is worse than the honest breakage of having none.
        remove_if_present(&cert_pem)?;
        remove_dir_if_present(&certs)?;
        return Ok(Vec::new());
    }

    fs::create_dir_all(root)?;
    set_mode(root, DIR_MODE)?;

    // Build the whole directory alongside, then exchange it in one step.
    let staging = root.join("certs.new");
    remove_dir_if_present(&staging)?;
    fs::create_dir_all(&staging)?;
    set_mode(&staging, DIR_MODE)?;

    let text = bundle(composed);
    write_file(&staging.join("ca-certificates.crt"), text.as_bytes())?;

    // OpenSSL's CApath: one PEM per root, named by subject hash, with a
    // sequence number to separate the occasional collision.
    let mut used: Vec<(String, u32)> = Vec::new();
    for root_entry in &composed.roots {
        let hash = &root_entry.parsed.subject_hash;
        let sequence = match used.iter_mut().find(|(h, _)| h == hash) {
            Some((_, n)) => {
                *n += 1;
                *n
            }
            None => {
                used.push((hash.clone(), 0));
                0
            }
        };
        write_file(&staging.join(format!("{hash}.{sequence}")), cert::to_pem(&root_entry.parsed.der).as_bytes())?;
    }

    exchange(&staging, &certs)?;

    // The default CAfile is a copy rather than a link: it is read through a
    // filesystem merge, and a plain file has no resolution to get wrong.
    write_file(&cert_pem, text.as_bytes())?;

    Ok(vec![
        certs.join("ca-certificates.crt").display().to_string(),
        cert_pem.display().to_string(),
        certs.display().to_string(),
    ])
}

/// Write a file whole or not at all: a reader never sees a partial store.
fn write_file(path: &Path, contents: &[u8]) -> io::Result<()> {
    let temporary = path.with_extension("tmp");
    fs::write(&temporary, contents)?;
    set_mode(&temporary, FILE_MODE)?;
    fs::rename(&temporary, path)
}

fn set_mode(path: &Path, mode: u32) -> io::Result<()> {
    fs::set_permissions(path, fs::Permissions::from_mode(mode))
}

fn remove_if_present(path: &Path) -> io::Result<()> {
    match fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e),
    }
}

fn remove_dir_if_present(path: &Path) -> io::Result<()> {
    match fs::remove_dir_all(path) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e),
    }
}

/// Put `staging` where `live` is, atomically, and remove what was there.
///
/// `RENAME_EXCHANGE` swaps the two directories in one syscall, so no reader
/// ever sees the directory absent, half-built, or holding a mixture of the
/// old roots and the new. When `live` does not exist yet there is nothing to
/// exchange with and a plain rename is atomic on its own.
fn exchange(staging: &Path, live: &Path) -> io::Result<()> {
    if !live.exists() {
        return fs::rename(staging, live);
    }
    let from = cstring(staging)?;
    let to = cstring(live)?;
    // SAFETY: both paths are live NUL-terminated strings for the call.
    let rc = unsafe {
        libc::renameat2(
            libc::AT_FDCWD,
            from.as_ptr(),
            libc::AT_FDCWD,
            to.as_ptr(),
            libc::RENAME_EXCHANGE,
        )
    };
    if rc != 0 {
        let error = io::Error::last_os_error();
        // A filesystem without RENAME_EXCHANGE (or a kernel that lacks the
        // syscall) still gets a correct store, just with a window in which
        // the directory is the new one before the old is gone. Better than
        // refusing to render.
        if matches!(error.raw_os_error(), Some(libc::EINVAL) | Some(libc::ENOSYS) | Some(libc::ENOTSUP)) {
            let previous = live.with_extension("previous");
            remove_dir_if_present(&previous)?;
            fs::rename(live, &previous)?;
            fs::rename(staging, live)?;
            return remove_dir_if_present(&previous);
        }
        return Err(error);
    }
    remove_dir_if_present(staging)
}

fn cstring(path: &Path) -> io::Result<std::ffi::CString> {
    std::ffi::CString::new(path.as_os_str().as_bytes())
        .map_err(|_| io::Error::new(io::ErrorKind::InvalidInput, "path holds a NUL"))
}

/// The store directory's files, for a status reply.
pub fn rendered_paths(root: &Path) -> Vec<String> {
    let mut out = Vec::new();
    for path in [root.join("certs").join("ca-certificates.crt"), root.join("cert.pem")] {
        if path.exists() {
            out.push(path.display().to_string());
        }
    }
    out
}

/// A stable identity for the shipped bundle, so a package upgrade is noticed
/// without watching for filesystem events: its length and modification time.
pub fn stamp(path: &Path) -> Option<(u64, i64)> {
    let meta = fs::metadata(path).ok()?;
    let modified = meta.modified().ok()?.duration_since(std::time::UNIX_EPOCH).ok()?.as_secs() as i64;
    Some((meta.len(), modified))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::store::{self, Addition};
    use std::path::PathBuf;

    const COMODO: &str = include_str!("../tests/fixtures/comodo-ecc.pem");
    const NETLOCK: &str = include_str!("../tests/fixtures/netlock-arany.pem");
    const MICROSEC: &str = include_str!("../tests/fixtures/microsec-2009.pem");

    fn shipped() -> String {
        let mut text = String::new();
        for _ in 0..store::MINIMUM_SHIPPED {
            text.push_str(COMODO);
            text.push_str(NETLOCK);
            text.push_str(MICROSEC);
        }
        text
    }

    fn scratch(name: &str) -> PathBuf {
        let path = std::env::temp_dir().join(format!("trustd-render-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&path);
        path
    }

    #[test]
    fn a_render_produces_every_artifact_and_is_reproducible() {
        let root = scratch("all");
        let composed = store::compose(&shipped(), &[], &[], None).unwrap();
        let paths = render(&root, &composed, Compat::Files).unwrap();
        assert_eq!(paths.len(), 3);

        let bundle_path = root.join("certs/ca-certificates.crt");
        let text = fs::read_to_string(&bundle_path).unwrap();
        assert_eq!(text.matches("BEGIN CERTIFICATE").count(), 3);
        assert!(text.contains("generated by trustd"));
        // The default CAfile holds the same set.
        assert_eq!(fs::read_to_string(root.join("cert.pem")).unwrap(), text);
        // One hashed file per root, named as OpenSSL looks them up.
        for entry in &composed.roots {
            let path = root.join("certs").join(format!("{}.0", entry.parsed.subject_hash));
            assert!(path.exists(), "missing {}", path.display());
            assert_eq!(cert::from_pem(&fs::read_to_string(&path).unwrap()).len(), 1);
        }
        // Rendering the same store again writes identical bytes.
        render(&root, &composed, Compat::Files).unwrap();
        assert_eq!(fs::read_to_string(&bundle_path).unwrap(), text);
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn a_distrusted_root_leaves_no_file_behind() {
        let root = scratch("distrust");
        let composed = store::compose(&shipped(), &[], &[], None).unwrap();
        render(&root, &composed, Compat::Files).unwrap();
        let victim = composed.roots.iter().find(|r| r.parsed.subject.contains("COMODO")).unwrap().clone();
        let hashed = root.join("certs").join(format!("{}.0", victim.parsed.subject_hash));
        assert!(hashed.exists());

        // Now distrust it and render again: the CApath entry must be gone,
        // or OpenSSL would keep trusting it through the directory.
        let after = store::compose(&shipped(), &[], &[victim.parsed.fingerprint.clone()], None).unwrap();
        render(&root, &after, Compat::Files).unwrap();
        assert!(!hashed.exists(), "a stale hashed file kept a distrusted root alive");
        let text = fs::read_to_string(root.join("certs/ca-certificates.crt")).unwrap();
        assert!(!text.contains(&victim.parsed.fingerprint));
        assert_eq!(text.matches("BEGIN CERTIFICATE").count(), 2);
        // And no staging directory is left lying about.
        assert!(!root.join("certs.new").exists());
        assert!(!root.join("certs.previous").exists());
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn mode_none_removes_what_a_previous_mode_wrote() {
        let root = scratch("none");
        let composed = store::compose(&shipped(), &[], &[], None).unwrap();
        render(&root, &composed, Compat::Files).unwrap();
        assert!(root.join("cert.pem").exists());

        let paths = render(&root, &composed, Compat::None).unwrap();
        assert!(paths.is_empty());
        assert!(!root.join("cert.pem").exists());
        assert!(!root.join("certs").exists(), "stale trust must not survive the switch to mode 0");
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn an_addition_is_named_in_the_bundle_for_a_person_reading_it() {
        let addition = Addition {
            name: "corp-ca".into(),
            der: cert::from_pem(MICROSEC).remove(0),
            purposes: vec![],
        };
        let mut text = String::new();
        for _ in 0..store::MINIMUM_SHIPPED {
            text.push_str(COMODO);
            text.push_str(NETLOCK);
        }
        let composed = store::compose(&text, &[addition], &[], None).unwrap();
        let rendered = bundle(&composed);
        assert!(rendered.contains("# added as corp-ca"));
        assert!(rendered.contains("3 root(s): 2 shipped, 1 added"));
    }

    #[test]
    fn compat_modes_map_to_the_registry_dword() {
        assert_eq!(Compat::from_dword(0), Compat::None);
        assert_eq!(Compat::from_dword(1), Compat::Files);
        assert_eq!(Compat::from_dword(2), Compat::Live);
        // Anything unrecognised renders rather than silently disabling trust.
        assert_eq!(Compat::from_dword(99), Compat::Files);
        assert_eq!(Compat::Files.as_dword(), 1);
    }
}
