[package]
name         = "dev.peios.trustd-debugsource"
architecture = "x86_64"
description  = "Debug sources for the Peios trust service and client"

[dependencies]
"dev.peios.trustd-debuginfo" = "= {{release}}"
"dev.peios.trust-debuginfo"  = "= {{release}}"

[files]
"@source:LICENSE"   = "usr/share/licenses/dev.peios.trustd-debugsource/LICENSE"
":licenses/**"      = "usr/share/licenses/dev.peios.trustd-debugsource/third-party"
":usr/src/debug/**" = "usr/src/debug"
