# Shared metadata for the production trustd package family. The composite
# expression is the exact selected licence closure of the locked Linux build:
# Peios elects MIT from permissive alternatives; Apache-only, BSD, ISC, and
# Unicode terms remain independently required by other crates.

format = "peipkg"

[package]
version      = "{{version}}-1"
architecture = "x86_64"
license      = "MIT AND Apache-2.0 AND BSD-3-Clause AND ISC AND Unicode-3.0"
license_class = "free"
homepage      = "https://peios.org"
